name: cookbook
description: A cookbook and skills guide for culinaryenthusiasts
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_svg: ^0.19.2+1
  flutter_gradient_colors: ^1.0.0
  flutter:
    sdk: flutter
  line_icons: ^0.2.0
  cupertino_icons: ^0.1.3
  route_transitions: ^1.0.2
  blurrycontainer: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/countries/
    - assets/countries/japaneese/
    - assets/countries/indian/
    - assets/countries/italian/
    - assets/countries/mexican/
    - assets/countries/french/
    - assets/icons/
    - assets/categories/
    - assets/chefs/
    - assets/chefs/gordon/
    - assets/chefs/thomas/
    - assets/chefs/vikas/
    - assets/chefs/clara/
    - assets/chefs/wolfgang/
    - assets/collections/
    - assets/collections/breakfast/
    - assets/collections/lunch/
    - assets/collections/soups/
    - assets/collections/dinner/
    - assets/collections/salads/
    - assets/seasons/
    - assets/fastfood/
    - assets/fastfood/sausages/
    - assets/Curated/
    - assets/healthy/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Bold.ttf